project_id = "rkrggssktzpczxvjhrxm"

[db]
pooler = { enabled = true, port = 6543, pool_mode = "transaction" }

[functions.create-onboarding-account]
verify_jwt = false

[functions.upsert-onboarding-session]
verify_jwt = false
